version: '3.7'
services:
    app:
        build:
            target: prod
        restart: always
    postgres:
        restart: always
        ports:
            - 5432:5432
    redis:
        restart: always
